name 'win_choco'
maintainer 'Progress'
maintainer_email 'michael.butler@progress.com'
license 'Apache-2.0'
description 'Installs/Configures win_choco'
version '0.1.0'
chef_version '>= 16.0'
depends 'chocolatey'
